name: Build and Deploy Vue App to Azure

on:
  push:
    branches:
      - main  # O 'master', la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Aquí compilamos Vue e inyectamos la URL de producción
      - name: Build Vue App
        run: npm run build
        env:
          VITE_CORTISENSE_API_URL: ${{ secrets.VITE_CORTISENSE_API_URL }}

      # Subimos la carpeta 'dist' (que contiene el HTML/JS compilado) a Azure
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cortisense-mockapi' # <-- Pon aquí el nombre de tu recurso de Vue en Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist # <-- Súper importante: solo subimos la carpeta compilada